
site_name: Docs4IT – מדריכים, פתרונות וידע מהשטח

theme:
  name: material
  language: he
  features:
    - content.code.copy
    - navigation.top
  palette:
    primary: deep purple
    accent: amber

nav:
  - דף הבית: index.md
  - אודות: about/index.md

  - התקנות:
      - התקנת Ubuntu Server: ubuntu-install/index.md
      - התקנת Apache HTTP Server על Ubuntu: web-server-ubuntu/index.md
      - התקנת Squid Reverse Proxy: squid-reverse-proxy/index.md
      - התקנת שרת פרוקסי קדמי (Forward Proxy) עם Squid: proxy-forward-install/index.md
      - מדריך התקנה Vmware: vmware-install/index.md
      - מדריך להתקנה של vmware: vmware-esxi-8-create-vm/index.md
      - מדריך להגדרת Windows Firewall: windows-firewall-guide/index.md

  - תקלות:
      - פתרון תקלות Azure/Teams/Outlook: aad-broker-troubleshooting/index.md

  - הסברים:
      - מדריך Sysinternals: sysinternals-tools/index.md
      - מדריך Wireshark: wireshark-guide/index.md
      - הסבר להתקנת Vmware: vmware-explained/index.md
      - הסבר לפקודות לינוקס: linux-explained/index.md
      - הסבר לפקודות Squid: squid-explained/index.md
      - הסבר לפקודות שרת ווב: web-server-explained/index.md
      - הסבר לפקודות Ubuntu: ubuntu-explained/index.md
      - הסבר לפקודות התקנת שרת פרוקסי קדמי עם Squid: proxy-forward-explained/index.md
      - פקודות בסיסיות ב־VIM: vim-guide/index.md
      - פקודות בסיסיות ב־NANO: nano-guide/index.md

  - סקריפטים כלים ופקודות:
      - סקריפטים שימושיים: it-scripts/index.md
      - פקודות תחזוקת וינדוס: windows-maintenance/index.md
      - מדריך מלא לניתוח איתחול מחשב: WPA_Boot_Analysis_Guide/index.md
      - מדריך עבודה עם NK2: NK2_to_Outlook_Contacts/index.md
      - כלים ניידים ושימושיים: portable-tools/index.md

extra_css:
  - stylesheets/extra.css


extra_javascript:
  - js/goatcounter.js


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
